### PR TITLE
YES_30_Enable_Star_Ratings_On_Category_Pages Magento 2 Done

### PR DESCRIPTION
**Pull request by ijazalise**
Done

### CODE REVIEW

**Comment by ijazalise** [comment]
Hi Ohadsc,
One yotpoListProduct is for (home page/category product listing page) and YotpoReviewRenderer  is for catalog search and catalog advance search page.

**Comment by ijazalise** [comment]
Hi Ohadsc,
One yotpoListProduct is for (home page/category product listing page) and YotpoReviewRenderer  is for catalog search and catalog advance search page.

**Comment by ohadsc** [comment]
@ijazalise the code in both classes is very similar, what do u think about moving it to a separate class that both YotpoListProduct & YotpoReviewRenderer will use?

**Comment by haroon-chaudhry** [comment]
@ohadsc this is not possible because both classes needs to extend base classes and override the functions to make it work.

**Comment by ohadsc** [comment]
@ijazalise  can u move the common logic out to a util class and use it for both YotpoListProduct and YotpoReviewRenderer?

**Comment by aberenshtein** [comment]
@haroon-chaudhry

**Comment by aberenshtein** [comment]
@ijazalise please also rebase

**Comment by ijazalise** [comment]
aberenshtein rebase done.

**Comment by haroon-chaudhry** [comment]
@ohadsc We have reviewed the possibility of refactoring the common code in Utility class but we believe it will be overdoing and we will end up adding more boilerplate code. The code in each class uses parent class overridden functions. If you also notice the code tries to use "this" which if moved in a different class would not work as required. 

I would keep this the way it is, since it's not lots of code anyway.

**Comment by ohadsc** [comment]
@haroon-chaudhry @ijazalise ok, thanks guys

**Comment by sa3iedsabbah** [comment]
Approved by QA

**Pull request merged**
