### PR TITLE
Added support for PHP 7.1

### PR DESCRIPTION
**Pull request by Tjitse-E**

### CODE REVIEW

**Comment by billykov** [comment]
Hey @Tjitse-E ,
Did you check the module works on 7.1?

**Comment by Tjitse-E** [comment]
@billykov we're currently using the module with PHP 7.1, I haven't seen any problems yet.

**Comment by sa3iedsabbah** [comment]
@ijazalise hi
last week we released a 2.2.6 for magento2
i need you to  rebase all current magento 2 branches.
thanks

**Comment by ijazalise** [comment]
Kindly create ticket on Jira.

**Comment by friendscottn** [comment]
Fixes #

**Pull request merged**
