### PR TITLE
review fixes

### PR DESCRIPTION
**Pull request by omryYotpo**
@dmitri86git need to sanity check this

### CODE REVIEW

**Comment by dmitri86git** [comment]
@omryYotpo 👍 You can merge it

**Comment by omryYotpo** [comment]
@dmitri86git Yo man...need another sanity check with 2.0.4

**Comment by dmitri86git** [comment]
@omryYotpo Looks fine 👍

**Comment by omryYotpo** [comment]
@j-bachman Can you talk to review ninja to stop bugging me?

**Comment by j-bachman** [comment]
⭐

**Comment by j-bachman** [comment]
@omryYotpo had a chat with review ninja, starred...

**Pull request merged**
