### PR TITLE
Yes 25 unable to pull product specs

### PR DESCRIPTION
**Pull request by ijazalise**
Done.

### CODE REVIEW

**Comment by aberenshtein** [comment]
@ijazalise this branch needs to be rebased

**Comment by ijazalise** [comment]
Rebase done.

**Comment by ohadsc** [comment]
seems like duplicate to https://github.com/YotpoLtd/magento2-plugin/pull/59 
if so, please delete this PR

**Comment by haroon-chaudhry** [comment]
This was branch and pull request you guys requested to create after we had created previous branch. Please delete that https://github.com/YotpoLtd/magento2-plugin/pull/59 and merge this one. We can't delete a PR since doesnt have access rights.

**Pull request merged**
